### ISSUE TITLE
Solutions merged into exercise

### ISSUE THREAD

**Issue by jaintj95** [udacity/deep-learning-v2-pytorch#317]
In the following pull request you merged the exercise notebook with solutions 

https://github.com/udacity/deep-learning-v2-pytorch/commit/0d69f2669d755f7031fa44b0d747d0874a6dba6d#diff-ae7662d58c8d54ec785f3db1e845a9d424b02657ff6d820072df7bd355fec1cd

See: https://knowledge.udacity.com/questions/550090

**Comment by ItamarRocha** [comment]
It's a mess. Including wrong solutions.

**Comment by abhiojha8** [comment]
This was resolved by commit - https://github.com/udacity/deep-learning-v2-pytorch/commit/ae8f4ac647ca0125a2cb1e8d1d1275701b975d21

**Comment by austin1howard** [comment]
@abhiojha8 your commit didn't resolve the solutions (which are broken/incorrect) in Part 2 introduced by PR #269...also that PR modified the vscode dotfile with the PR user's specific paths on his workstation.

**Comment by lemairecarl** [comment]
That's true, there are solutions in Part 2 Exercices, and messy outputs.
